/* Patel Marketing V4 — sign in, account, settings, help.
   ------------------------------------------------------------------
   Sign-in is Supabase phone OTP. The code is generated by Supabase and
   carried by our Send SMS edge function; nothing about that route is in
   this repo. The five test numbers hold a PIN instead of a texted code
   so the whole flow can be walked without spending money on SMS — the
   PIN is checked by Supabase, not here, so a number that is not on the
   list simply gets the ordinary texted code.
   ------------------------------------------------------------------ */
(function(){
'use strict';
const {esc} = PM;
const {icon, sheet, closeSheet, toast, empty, header, headerAction, waitingForSession} = UI;
const view = () => document.getElementById('view');
const scrollTop = () => { const m=document.querySelector('main'); if(m) m.scrollTop=0; window.scrollTo(0,0); };

/* ============ sign in ============================================== */
let PENDING = null;      // digits awaiting a code, or null

PM.route('/signin', function(){
  if(waitingForSession('Sign in')) return;
  if(PM.signedIn()){ PM.go('/account', true); return; }
  header({back:true, title:'Sign in'});
  drawPhoneStep();
  scrollTop();
});

function drawPhoneStep(){
  view().innerHTML =
    '<div class="card card-pad" style="margin-top:16px">'+
      '<h2 style="font-size:1.1rem;font-weight:750;letter-spacing:-.02em">Your phone number</h2>'+
      '<p class="tiny muted" style="margin:6px 0 14px;line-height:1.55">'+
        'We text a code to the number we have on file for your shop. '+
        'Trade rates and the order pad open once you are in.</p>'+
      '<label class="field"><span>Mobile number</span>'+
        '<div class="row"><span class="badge badge-quiet">+91</span>'+
        '<input class="input grow" id="siPhone" type="tel" inputmode="numeric" maxlength="10" '+
        'autocomplete="tel-national" placeholder="10 digits" enterkeyhint="go"></div></label>'+
      '<div id="siErr"></div>'+
      '<button class="btn btn-primary btn-lg btn-block" id="siGo" style="margin-top:6px">Continue</button>'+
      '<p class="tiny muted" style="margin-top:12px;line-height:1.5">'+
        (PM.CFG.auth && PM.CFG.auth.noAccessMessage
          ? esc(PM.CFG.auth.noAccessMessage)+' Ask us to add you and try again.'
          : '')+'</p>'+
    '</div>'+
    '<div class="menulist" style="margin-top:14px">'+
      '<button class="menurow" id="siNew">'+icon('user')+
        '<div class="grow"><b>Shopping for yourself?</b>'+
        '<small>Sign up as a customer of a shop near you</small></div>'+
        '<span class="chev">'+icon('chev')+'</span></button>'+
      '<a class="menurow" href="#/help">'+icon('info')+
        '<div class="grow"><b>Trouble signing in?</b><small>What to check, and how to reach us</small></div>'+
        '<span class="chev">'+icon('chev')+'</span></a>'+
    '</div>'+
    '<p class="tiny muted" style="text-align:center;margin-top:16px">'+
      esc(window.PMAuth ? PMAuth.diagLine() : 'sign-in library missing')+' · v4</p>';

  const input = document.getElementById('siPhone');
  const go = document.getElementById('siGo');
  input.addEventListener('keydown', e => { if(e.key==='Enter'){ e.preventDefault(); go.click(); } });
  go.onclick = async function(){
    const digits = PM.dg(input.value).slice(-10);
    const err = document.getElementById('siErr');
    if(digits.length!==10){
      err.innerHTML = '<div class="strip" style="background:var(--bad-wash);color:var(--bad)">'+
        'That number needs ten digits.</div>';
      return;
    }
    err.innerHTML = '';
    PENDING = digits;
    // A test number never sends an SMS. Every other number does, and
    // each one costs money, so the button says what is about to happen.
    if(PMAuth.isTestNumber(digits)){ drawPinStep(digits); return; }
    go.disabled = true; go.textContent = 'Sending…';
    const {error} = await PMAuth.sendOtp(digits);
    go.disabled = false; go.textContent = 'Continue';
    if(error){
      err.innerHTML = '<div class="strip" style="background:var(--bad-wash);color:var(--bad)">'+
        esc(PMAuth.friendlyAuthError(error))+'</div>';
      return;
    }
    drawOtpStep(digits);
  };
  document.getElementById('siNew').onclick = () => sheet({
    title:'Shopping for yourself?',
    body:'<p class="muted" style="line-height:1.6">Put in your phone number above and continue. '+
      'If we do not know it yet, the next screen lets you sign up as a customer — '+
      'you will see the shop’s prices and offers rather than trade rates.</p>',
    foot:'<button class="btn btn-primary btn-block" data-sheet-close>Got it</button>'});
}

function drawOtpStep(digits){
  view().innerHTML = codeCard(digits, 'We texted a 6-digit code to +91 '+digits+'.',
    'Code from the SMS', 6, 'numeric');
  wireCodeStep(digits, false);
}
function drawPinStep(digits){
  view().innerHTML = codeCard(digits,
    'This is a test account, so there is no SMS — put in its PIN.', 'PIN', 6, 'numeric');
  wireCodeStep(digits, true);
}
function codeCard(digits, blurb, label, len){
  return '<div class="card card-pad" style="margin-top:16px">'+
    '<h2 style="font-size:1.1rem;font-weight:750;letter-spacing:-.02em">Check the code</h2>'+
    '<p class="tiny muted" style="margin:6px 0 14px;line-height:1.55">'+esc(blurb)+'</p>'+
    '<label class="field"><span>'+esc(label)+'</span>'+
      '<input class="input" id="siCode" inputmode="numeric" autocomplete="one-time-code" '+
      'maxlength="'+len+'" placeholder="'+'•'.repeat(len)+'" enterkeyhint="go" '+
      'style="letter-spacing:.35em;font-size:1.1rem;font-weight:700;text-align:center"></label>'+
    '<div id="siErr"></div>'+
    '<button class="btn btn-primary btn-lg btn-block" id="siVerify">Sign in</button>'+
    '<div class="btnrow" style="margin-top:8px">'+
      '<button class="btn btn-quiet" id="siBack">Change number</button>'+
      '<button class="btn btn-quiet" id="siResend">Send again</button>'+
    '</div></div>';
}
function wireCodeStep(digits, isPin){
  const code = document.getElementById('siCode');
  const btn = document.getElementById('siVerify');
  const err = document.getElementById('siErr');
  setTimeout(() => code.focus(), 80);
  code.addEventListener('keydown', e => { if(e.key==='Enter'){ e.preventDefault(); btn.click(); } });
  document.getElementById('siBack').onclick = () => { PENDING=null; drawPhoneStep(); };
  document.getElementById('siResend').onclick = async function(){
    if(isPin){ toast('Test accounts use a fixed PIN'); return; }
    this.disabled = true; this.textContent = 'Sending…';
    const {error} = await PMAuth.sendOtp(digits);
    this.disabled = false; this.textContent = 'Send again';
    toast(error ? PMAuth.friendlyAuthError(error) : 'Code sent again');
  };
  btn.onclick = async function(){
    const v = PM.dg(code.value);
    if(!v){ err.innerHTML = fail('Put in the code first.'); return; }
    btn.disabled = true; btn.textContent = 'Checking…';
    const {error} = isPin ? await PMAuth.signInWithPin(digits, v)
                          : await PMAuth.verifyOtp(digits, v);
    if(error){
      btn.disabled = false; btn.textContent = 'Sign in';
      err.innerHTML = fail(PMAuth.friendlyAuthError(error));
      return;
    }
    btn.textContent = 'Signing in…';
    const s = await PM.refreshSession();
    UI.cartbar(); UI.tabbar();
    if(!s){
      // The token is real but there is no allowlist row — a number
      // Supabase accepted that we do not know yet. Offer the sign-up
      // rather than dead-ending on "we do not recognise that number".
      btn.disabled = false; btn.textContent = 'Sign in';
      drawSignupStep(digits);
      return;
    }
    toast('Signed in — '+PM.roleLabel().toLowerCase());
    PM.go('/account', true);
  };
  const fail = m => '<div class="strip" style="background:var(--bad-wash);color:var(--bad)">'+esc(m)+'</div>';
}

function drawSignupStep(digits){
  view().innerHTML =
    '<div class="card card-pad" style="margin-top:16px">'+
      '<h2 style="font-size:1.1rem;font-weight:750;letter-spacing:-.02em">Nearly there</h2>'+
      '<p class="tiny muted" style="margin:6px 0 14px;line-height:1.55">'+
        'Your number checked out, but we do not have you on our list yet. '+
        'Tell us who you are and you can start browsing as a customer. '+
        'A dealer account is set up by us — send us a message and we will do it.</p>'+
      '<label class="field"><span>Your name</span>'+
        '<input class="input" id="suName" autocomplete="name" placeholder="Name"></label>'+
      '<label class="field"><span>City</span>'+
        '<input class="input" id="suCity" autocomplete="address-level2" placeholder="Hubli"></label>'+
      '<div id="siErr"></div>'+
      '<button class="btn btn-primary btn-lg btn-block" id="suGo">Create my account</button>'+
      '<button class="btn btn-quiet btn-block" id="suWa" style="margin-top:8px">'+
        icon('wa')+'Ask for a dealer account</button>'+
    '</div>';
  document.getElementById('suGo').onclick = async function(){
    const name = document.getElementById('suName').value.trim();
    const city = document.getElementById('suCity').value.trim();
    const err = document.getElementById('siErr');
    if(!name){ err.innerHTML = '<div class="strip" style="background:var(--bad-wash);'+
      'color:var(--bad)">Please put in your name.</div>'; return; }
    this.disabled = true; this.textContent = 'Creating…';
    try{
      const {error} = await PMAuth.sb.rpc('self_signup_end_customer',
        {p_name:name, p_city:city||null});
      if(error) throw error;
    }catch(e){
      this.disabled = false; this.textContent = 'Create my account';
      err.innerHTML = '<div class="strip" style="background:var(--bad-wash);color:var(--bad)">'+
        esc((e && e.message) || 'Could not create the account just now.')+'</div>';
      return;
    }
    await PM.refreshSession();
    UI.cartbar(); UI.tabbar();
    toast('Welcome');
    PM.go('/account', true);
  };
  document.getElementById('suWa').onclick = () => {
    const n = String(PM.CFG.whatsapp||'917892967505').replace(/\D/g,'');
    window.open('https://wa.me/'+n+'?text='+encodeURIComponent(
      'Hello Patel Marketing, I would like a dealer account. My number is +91'+digits+'.'),
      '_blank','noopener');
  };
}

/* ============ account ============================================== */
PM.route('/account', function(){
  if(waitingForSession('You')) return;
  header({back:false, title:'You', actions:[
    headerAction('cog','onclick="location.hash=\'#/settings\'"','Settings'),
  ]});
  document.getElementById('topbar').querySelector('.brandname').innerHTML =
    'Your account<small>'+esc(PM.roleLabel())+'</small>';

  if(!PM.signedIn()){
    view().innerHTML =
      '<div class="card card-pad" style="margin-top:16px;text-align:center">'+
        '<div class="avatar" style="margin:4px auto 12px;background:var(--surface-2);color:var(--ink-3)">'+
          icon('user')+'</div>'+
        '<h2 style="font-size:1.05rem;font-weight:730">Not signed in</h2>'+
        '<p class="tiny muted" style="margin:6px 0 14px;line-height:1.55">'+
          'Sign in with your phone number to see trade rates, build an order '+
          'and keep your order history.</p>'+
        '<a class="btn btn-primary btn-block" href="#/signin">Sign in</a>'+
      '</div>'+ guestMenu();
    scrollTop();
    return;
  }

  const S = PM.SESS;
  view().innerHTML =
    '<div class="card card-pad" style="margin-top:16px">'+
      '<div class="row" style="gap:13px">'+
        '<div class="avatar">'+(S.photo
          ? '<img src="'+esc(S.photo)+'" alt="">'
          : esc(initials(S.name)))+'</div>'+
        '<div class="grow"><b style="font-size:1rem;font-weight:730;display:block">'+esc(S.name)+'</b>'+
          '<div class="tiny muted">'+esc(S.shop || S.city || '')+'</div>'+
          '<div class="row" style="gap:5px;margin-top:5px">'+
            '<span class="badge badge-brand">'+esc(PM.roleLabel())+'</span>'+
            '<span class="badge badge-quiet num">+91 '+esc((S.phone||'').slice(-10))+'</span>'+
          '</div></div>'+
      '</div>'+
      (S.gst ? '<div class="tiny muted" style="margin-top:10px">GST '+esc(S.gst)+'</div>' : '')+
    '</div>'+

    '<div class="menulist" style="margin-top:14px">'+
      row('receipt','Your orders','Everything you have sent us','#/orders')+
      (PM.canOrder() ? row('bag','Your current order',
        PM.cartCount() ? PM.cartCount()+' '+PM.plural(PM.cartCount(),'item')+' waiting'
                       : 'Nothing in it yet', '#/cart') : '')+
      row('heart','Saved','Products you kept on this phone','#/saved')+
    '</div>'+

    (PM.isOffice() ? '<div class="menulist" style="margin-top:14px">'+
      row('receipt','Order book','Every order that came in','../orders.html')+
      row('edit','Admin panel','Rates, photos, stock and people','../admin.html')+
      '</div>' : '')+

    (PM.isDealer() ? '<div class="menulist" style="margin-top:14px">'+
      row('tag','Your shop screen','Offers you show your own customers','../shop.html')+
      row('repeat','Exchange','Stock other dealers are offering','../exchange.html')+
      '</div>' : '')+

    '<div class="menulist" style="margin-top:14px">'+
      row('cog','Settings','Theme, text size, motion','#/settings')+
      row('info','Help','How this works, and how to reach us','#/help')+
      row('wa','Message us','WhatsApp '+esc(PM.CFG.whatsapp||''),'#','data-wa="1"')+
    '</div>'+

    '<div style="margin-top:14px"><button class="btn btn-danger btn-block" id="acOut">'+
      icon('out')+'Sign out</button></div>'+
    '<p class="tiny muted" style="text-align:center;margin-top:14px">'+
      'Patel Marketing · v4 · build '+(window.PMAuth?PMAuth.BUILD:'?')+'</p>';
  scrollTop();

  const wa = view().querySelector('[data-wa]');
  if(wa) wa.onclick = e => {
    e.preventDefault();
    const n = String(PM.CFG.whatsapp||'917892967505').replace(/\D/g,'');
    window.open('https://wa.me/'+n, '_blank','noopener');
  };
  document.getElementById('acOut').onclick = () => sheet({
    title:'Sign out?',
    body:'<p class="muted">Your saved list and anything in your order stay on this phone. '+
         'Signing back in costs another texted code.</p>',
    foot:'<div class="btnrow"><button class="btn btn-secondary" data-sheet-close>Stay signed in</button>'+
         '<button class="btn btn-danger" id="yesOut">Sign out</button></div>',
    wire(el){ el.querySelector('#yesOut').onclick = async () => {
      closeSheet();
      await PMAuth.signOut();
      await PM.refreshSession();
      UI.cartbar(); UI.tabbar();
      toast('Signed out');
      PM.go('/', true);
    }; }
  });
});

const guestMenu = () => '<div class="menulist" style="margin-top:14px">'+
  row('heart','Saved','Products you kept on this phone','#/saved')+
  row('cog','Settings','Theme, text size, motion','#/settings')+
  row('info','Help','How this works, and how to reach us','#/help')+
  '</div>';
const row = (ic, title, sub, href, extra) =>
  '<a class="menurow" href="'+href+'"'+(extra?' '+extra:'')+'>'+icon(ic)+
  '<div class="grow"><b>'+esc(title)+'</b><small>'+esc(sub)+'</small></div>'+
  '<span class="chev">'+icon('chev')+'</span></a>';
const initials = n => String(n||'?').trim().split(/\s+/).slice(0,2)
  .map(w => w[0]).join('').toUpperCase() || '?';

/* ============ settings ============================================= */
/* Two independent choices, not one list. WHICH palette (sky, teal,
   emerald, charcoal) and whether it runs LIGHT or DARK. V3 mixed them —
   "charcoal" was the dark theme — so picking dark meant giving up your
   colour, and there was no way to have sky at night. Here every palette
   has both, and Auto follows the phone.

   Sky is the default because it is the colour the firm has been using.
   Auto is the default mode. */
const THEMES = [
  ['sky','Sky'], ['teal','Teal'], ['emerald','Emerald'], ['charcoal','Charcoal'],
];
const THEME_KEY='v4_pm_theme', MODE_KEY='v4_pm_mode';
const themeIds = THEMES.map(t => t[0]);

function readTheme(){
  let v;
  try{ v = localStorage.getItem(THEME_KEY); }catch(e){}
  // V4's first release stored light/dark/auto under this key. Anyone
  // carrying one of those gets sky, and their old value becomes the mode.
  if(v==='light'||v==='dark'||v==='auto'){
    try{ if(!localStorage.getItem(MODE_KEY)) localStorage.setItem(MODE_KEY, v); }catch(e){}
    v = null;
  }
  return themeIds.indexOf(v)>=0 ? v : 'sky';
}
function readMode(){
  let v; try{ v = localStorage.getItem(MODE_KEY); }catch(e){}
  return (v==='light'||v==='dark'||v==='auto') ? v : 'auto';
}
const systemDark = () => {
  try{ return window.matchMedia('(prefers-color-scheme: dark)').matches; }catch(e){ return false; }
};
const resolvedMode = () => { const m = readMode(); return m==='auto' ? (systemDark()?'dark':'light') : m; };

function applyTheme(){
  const root = document.documentElement;
  root.setAttribute('data-theme', readTheme());
  root.setAttribute('data-mode',  resolvedMode());
  // The browser chrome should match the bar it sits against, not a colour
  // fixed at build time — otherwise switching to dark leaves a white strip
  // above the header on Android.
  const m = document.querySelector('meta[name="theme-color"]');
  if(m){
    const c = getComputedStyle(root).getPropertyValue('--surface').trim();
    if(c) m.setAttribute('content', c);
  }
}
const PREF = {
  fs:     {key:'v4_pm_fs',    def:'m',    apply(v){ document.documentElement.setAttribute('data-fs', v); }},
  motion: {key:'v4_pm_motion',def:'full', apply(v){
    document.documentElement.setAttribute('data-motion', v==='off'?'off':'full'); }},
};
function pref(name){ try{ return localStorage.getItem(PREF[name].key) || PREF[name].def; }
                     catch(e){ return PREF[name].def; } }
function setPref(name, v){
  try{ localStorage.setItem(PREF[name].key, v); }catch(e){}
  PREF[name].apply(v);
}
function applyPrefs(){
  applyTheme();
  Object.keys(PREF).forEach(k => PREF[k].apply(pref(k)));
}
applyPrefs();
// Auto has to keep following the phone after load — a dealer whose screen
// switches at sunset should not have to reload to get the dark palette.
try{
  window.matchMedia('(prefers-color-scheme: dark)')
    .addEventListener('change', () => { if(readMode()==='auto') applyTheme(); });
}catch(e){}

PM.route('/settings', function(){
  header({back:true, title:'Settings'});
  const seg = (name, opts) => '<div class="segmented">'+opts.map(([v,l]) =>
    '<button data-pref="'+name+'" data-val="'+v+'"'+(pref(name)===v?' class="on"':'')+'>'+
    esc(l)+'</button>').join('')+'</div>';
  const modeSeg = () => '<div class="segmented">'+
    [['light','Light'],['dark','Dark'],['auto','Auto']].map(([v,l]) =>
      '<button data-mode="'+v+'"'+(readMode()===v?' class="on"':'')+'>'+l+'</button>').join('')+
    '</div>';
  // Each swatch is painted by the palette it selects, so the choice is the
  // colour rather than a word for it.
  const swatches = () => {
    // The mode comes from the document, not from storage. They should agree,
    // and when they do not it is the document the reader is looking at — a
    // swatch that previews itself in light while the screen is dark is worse
    // than useless.
    const m = document.documentElement.getAttribute('data-mode') || 'light';
    return '<div class="swatchrow">'+THEMES.map(([id,label]) =>
      '<button class="swatch'+(readTheme()===id?' on':'')+'" data-theme-pick="'+id+'" '+
      'data-theme="'+id+'" data-mode="'+m+'" aria-label="'+esc(label)+'">'+
      '<span class="swatch-dot"></span><span class="swatch-name">'+esc(label)+'</span></button>').join('')+
      '</div>';
  };

  view().innerHTML =
    '<div class="card card-pad" style="margin-top:16px">'+
      '<div class="setrow" style="display:block"><div class="grow" style="margin-bottom:10px">'+
        '<b>Colour</b><small>Four palettes, each with a light and a dark</small></div>'+
        swatches()+'</div>'+
      '<div class="setrow"><div class="grow"><b>Light or dark</b>'+
        '<small>Auto follows your phone — right now it is '+resolvedMode()+'</small></div>'+
        modeSeg()+'</div>'+
      '<div class="setrow"><div class="grow"><b>Text size</b>'+
        '<small>Everything scales together</small></div>'+
        seg('fs',[['s','S'],['m','M'],['l','L'],['xl','XL']])+'</div>'+
      '<div class="setrow"><div class="grow"><b>Motion</b>'+
        '<small>Turn off if animation makes it hard to read</small></div>'+
        seg('motion',[['full','On'],['off','Off']])+'</div>'+
    '</div>'+

    '<section class="section"><div class="section-head"><h2>This app</h2></div>'+
      '<div class="card card-pad">'+
        '<div class="setrow"><div class="grow"><b>Install on your phone</b>'+
          '<small>Opens like an app, works with no signal</small></div>'+
          '<button class="btn btn-secondary btn-sm" id="setInstall">Install</button></div>'+
        '<div class="setrow"><div class="grow"><b>Refresh the catalogue</b>'+
          '<small>Pull the newest rates and photos now</small></div>'+
          '<button class="btn btn-secondary btn-sm" id="setRefresh">Refresh</button></div>'+
        '<div class="setrow"><div class="grow"><b>Version</b>'+
          '<small>v4 · build '+(window.PMAuth?PMAuth.BUILD:'?')+'</small></div>'+
          '<a class="btn btn-quiet btn-sm" href="../index.html">Old catalogue</a></div>'+
      '</div></section>'+

    '<p class="tiny muted" style="text-align:center;margin-top:16px;line-height:1.6">'+
      'Saved products and anything in your order are kept on this phone only.<br>'+
      'Your name, shop and orders are kept with your account.</p>';
  scrollTop();

  view().querySelectorAll('[data-pref]').forEach(b => b.onclick = () => {
    setPref(b.getAttribute('data-pref'), b.getAttribute('data-val'));
    b.parentElement.querySelectorAll('button').forEach(x => x.classList.remove('on'));
    b.classList.add('on');
  });
  const repaint = () => { applyTheme(); PM.dispatch(); };
  view().querySelectorAll('[data-theme-pick]').forEach(b => b.onclick = () => {
    try{ localStorage.setItem(THEME_KEY, b.getAttribute('data-theme-pick')); }catch(e){}
    repaint();
  });
  view().querySelectorAll('.segmented [data-mode]').forEach(b => b.onclick = () => {
    try{ localStorage.setItem(MODE_KEY, b.getAttribute('data-mode')); }catch(e){}
    repaint();
  });
  document.getElementById('setInstall').onclick = () => {
    if(window.PM_INSTALL){ window.PM_INSTALL.prompt(); window.PM_INSTALL = null; toast('Follow the prompt'); }
    else sheet({title:'Install this app',
      body:'<p class="muted" style="line-height:1.65">On Android, open the browser menu and choose '+
        '<b>Install app</b> or <b>Add to Home screen</b>.<br><br>'+
        'On an iPhone, tap the share button and choose <b>Add to Home Screen</b>.<br><br>'+
        'It then opens like any other app, and the catalogue keeps working with no signal.</p>',
      foot:'<button class="btn btn-primary btn-block" data-sheet-close>Got it</button>'});
  };
  document.getElementById('setRefresh').onclick = async function(){
    this.disabled = true; this.textContent = 'Refreshing…';
    try{
      if('caches' in window) for(const k of await caches.keys()) await caches.delete(k);
      await PM.loadCatalogue();
      toast('Catalogue refreshed');
    }catch(e){ toast('Could not refresh — check your signal'); }
    this.disabled = false; this.textContent = 'Refresh';
  };
});

/* ============ help ================================================= */
PM.route('/help', function(){
  header({back:true, title:'Help'});
  const q = (t,b) => '<div class="setrow"><div class="grow"><b>'+esc(t)+'</b>'+
    '<small style="line-height:1.55">'+b+'</small></div></div>';
  view().innerHTML =
    '<div class="card card-pad" style="margin-top:16px">'+
      q('Why can I not see rates?','Trade rates are for dealer accounts. Sign in with the number '+
        'we have on file, or message us to be added.')+
      q('The code did not arrive','Give it a minute, then tap <b>Send again</b>. If it still does '+
        'not come, message us on WhatsApp and we will check the number we hold for you.')+
      q('Some products show no rate','About 130 products have no rate on file yet. They still go '+
        'on an order with the rate left open — that is exactly when to ask us.')+
      q('Sold in boxes','Where a supplier sets a minimum, quantities move in that step. A product '+
        'sold in sixes goes 6, 12, 18.')+
      q('Does it work without signal?','Once installed, the catalogue and your saved list open '+
        'offline. Signing in and sending an order need a connection.')+
      q('What does the office see?','The name, shop and phone you type on the order screen, the '+
        'lines and quantities, and anything you add in the note.')+
    '</div>'+
    '<div style="margin-top:14px"><button class="btn btn-primary btn-block" id="hpWa">'+
      icon('wa')+'Message us on WhatsApp</button></div>'+
    '<p class="tiny muted" style="text-align:center;margin-top:14px">'+
      esc(PM.CFG.firm||'Patel Marketing')+' · '+esc(PM.CFG.tagline||'')+'<br>'+
      'v4 · '+esc(window.PMAuth?PMAuth.diagLine():'')+'</p>';
  scrollTop();
  document.getElementById('hpWa').onclick = () => {
    const n = String(PM.CFG.whatsapp||'917892967505').replace(/\D/g,'');
    window.open('https://wa.me/'+n, '_blank','noopener');
  };
});

window.PM_PREFS = {pref, setPref, applyPrefs, applyTheme, readTheme, readMode, THEMES};
})();
